### ISSUE TITLE
I think you didn't renew the domain

### ISSUE THREAD

**Issue by MrPeker** [cagataycali/url-shortener#18]
I can't access to demo page on shortener.cagatay.pro

**Comment by cagataycali** [comment]
You absolutely right, thanks for feedback, I’ll reactivate demo shortener as soon as possible. ⚡️

**Comment by cagataycali** [comment]
Redirected to https://shortener.cagatay.dev

Thx for feedback!

**Comment by MrPeker** [comment]
You're welcome, thanks
