### ISSUE TITLE
URLs can get taken emoji URL

### ISSUE THREAD

**Issue by tarekis** [cagataycali/url-shortener#7]
Demo deploy of repo (http://xn--7biv418msua.ws/) shortened a URL to a seemingly already taken URL.
Requesting with 
```
{
    url: "https://materialdesignicons.com/",
    emoji: true
}
```
returns
```
{
    message: "Do not do bad things to the server. Contributions welcome. http://🌍✌🏼.ws/♥☎💻❤",
    💩: "https://materialdesignicons.com/",
    😻: "🌍✌🏼.ws/☎📞😍♥❤📩💘🎶"
}
```

The emoji URL redirects me to https://hacktiv8.com/ tho.

**Comment by cagataycali** [comment]
Sorry for that, I noticed the error. I will fix it today and add a few features.

**Comment by tarekis** [comment]
Cool, thanks for the heads up! Amazing project btw, emoji links are the new best thing now, lol!

**Comment by cagataycali** [comment]
I think I fixed your issue, could you please check new version?
